config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :payment_intents

  resources :bookings, only: %i[index show] do
    resources :precheckins, only: %i[new create show]
  end

  resources :cautions, only: %i[index show]

  resources :hold, only: [:create]

  namespace :webhooks do
    resources :bookings, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :guest
  belongs_to :property
  has_one :caution, dependent: :destroy
  has_one :precheckin, dependent: :destroy

  validates :lodgify_id, presence: true, uniqueness: true
end

app/models/caution.rb
class Caution < ApplicationRecord
  belongs_to :booking

  # validates :name, :amount, presence: true
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :bookings, dependent: :destroy
end

app/models/precheckin.rb
class Precheckin < ApplicationRecord
  belongs_to :booking
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :lodgify_id, presence: true, uniqueness: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :property
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @caution = @booking.caution
  end
end

app/controllers/cautions_controller.rb
class CautionsController < ApplicationController
  before_action :set_caution, only: %i[show update destroy]

  def index
    @cautions = Caution.all
  end

  def show
    @caution = Caution.find(params[:id])
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @caution = Caution.new
  end

  def create
    @caution = Caution.new(caution_params)
    @booking = Booking.find(params[:booking_id])
    @caution.booking = @booking
    if @caution.save
      redirect_to booking_path(@booking), notice: "Caution was successfully created."
    else
      render :new
    end
  end

  def update
    if @caution.update(caution_params)
      redirect_to @caution, notice: "Caution was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @caution.destroy
    redirect_to cautions_url, notice: "Caution was successfully destroyed."
  end

  private

  def set_caution
    @caution = Caution.find(params[:id])
  end

  def caution_params
    params.require(:caution).permit(:name, :amount)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @bookings_of_today = Booking.where("arrival = ?", Date.today)
  end
end

app/controllers/payment_intents_controller.rb
class PaymentIntentsController < ApplicationController
  def create
    payment_intents = Stripe::PaymentIntent.create(
      amount: 1000,
      currency: 'eur',
      description: 'Example payment intent',
      statement_descriptor: 'NOCNOC submit',
      payment_method_types: ['card']
    )

    render json: {
      id: payment_intents.id,
      client_secret: payment_intents.client_secret
    }
  end
end

app/controllers/precheckins_controller.rb
class PrecheckinsController < ApplicationController
  before_action :set_booking, only: %i[new create]

  def new
    @guest      = @booking.guest
    @property   = @booking.property
    @precheckin = Precheckin.new
  end

  def create
    @precheckin = Precheckin.new(precheckin_params)
    @precheckin.booking = @booking

    if @precheckin.save
      redirect_to booking_precheckin_path(@precheckin.booking, @precheckin)
    else
      flash[:alert] = 'Something went wrong'
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @precheckin = Precheckin.find(params[:id])
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def precheckin_params
    params.require(:precheckin).permit(
      :first_name,
      :last_name,
      :email,
      :stripe_payment_id
    )
  end
end

app/controllers/webhooks/bookings_controller.rb
class Webhooks::BookingsController < ActionController::Base
  skip_before_action :verify_authenticity_token, only: %i[create]

  def create
    json = params.to_json
    json_parsed = JSON.parse(json)
    booking = json_parsed["_json"][0]["booking"]

    ## make sure the property is in the database
    property_id = booking["property_id"]
    PropertyInfoByIdService.new(property_id).call

    ## update or create the booking
    booking_id = booking["id"]
    BookingByIdService.new(booking_id).call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ## recuperer le montant de la caution
  # def get_amount(caution)
  #   caution.split(' ').filter { |word| word.chars.include?("€") }.first.chars.delete_if { |c| c == "€" }.join.gsub(",", ".").to_f if caution.include?("€")
  # end

  def get_amount(caution)
    result = caution.split(' ').filter { |word| word[0..-2] == word[0..-2].to_i.to_s }.filter { |number| number.length >= 3}.first.to_i
    result == 0 ? 1000 : result
  end

  # def get_phone(phone)
  #   phone_without_space = phone.chars.delete_if { |c| c == " " }.join
  #   phone_without_space.chars[0..2].join == "+33" ? "0#{phone_without_space[3..-1]}" : phone_without_space
  # end

  def get_image_url(image_url)
    image_url.chars[2..-1].join
  end

  # get_image_url("//l.icdbcdn.com/oh/0f987734-d443-40da-877c-f8c426e79de2.jpg?f=32")

end

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="title">Bookings (<%= @bookings.count %>)</h1>
  <% if @bookings.empty? %>
    <p>There are no bookings.</p>
  <% else %>
    <div class="bookings">
      <% @bookings.each do |booking| %>
        <div class="booking">
          <%= link_to booking_path(booking) do %>
            <p>id: <%= booking.id %></p>
            <p>lodgify_id: <%= booking.lodgify_id %></p>
            <p>property: <%= booking.property.name %></p>
            <p>guest: <%= booking.guest.name %></p>
            <p>arrival: <%= booking.arrival %></p>
            <p>departure: <%= booking.departure %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

app/views/cautions/_form.html.erb
<%= form_with(model: @caution) do |form| %>
  <% if @caution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caution.errors.count, "error") %> prohibited this caution from being saved:</h2>

      <ul>
        <% caution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cautions/index.html.erb
<h1>rpz</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @cautions.each  do |caution|%>
      <tr>
        <td><%= caution.name %></td>
        <td><%= caution.amount %></td>
        <td><%= link_to 'Show', caution_path(caution)%></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/cautions/new.html.erb
<h1>New Product</h1>

<%= render 'form', caution: @caution %>
<%= link_to 'Back', cautions_path %>

app/views/cautions/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @caution.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @caution.amount %>
</p>


<%= link_to 'Back', cautions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CautionNocnoc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <!-- Stripe -->
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%# <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Dashboard</h1>
<h2>Listes de toutes les réservations du jour</h2>
<div class="toto">
  <% ["Appartement", "Nom", "Pre-checkin", "ETA", "Etat caution"].each do |label| %>
    <p> <%= label %> </p>
  <% end %>
</div>
<% @bookings_of_today.each do |booking| %>
    <p>Appartement: <%= booking.property.name %></p>
    <p><%= booking.guest.name %></p>
    <p>Pre-checkin: TO DO</p>
    <p>ETA : TO DO</p>
    <p>Etat caution : TO DO</p>
    <p>Lien formulaire</p>
    <br>
<% end %>

<a href="#">azertyuio</a>

app/views/precheckins/new.html.erb
<%= image_tag "photo-tupin.jpg", class: 'photo-banner'  %>

<div class="container">
  <div class="CheckIn">
    <div class="CheckIn-infos">
      <%= image_tag "logo-nocnoc.png", class: 'logo'  %>
      <h1>Détails réservation</h1>
      <p><%= @property.name %> - <%= @property.address %>, <%= @property.zip %> <%= @property.city %></p>
      <p>CI : <%= @booking.arrival %></p>
      <p>C0 : <%= @booking.departure %></p>
    </div>
    <div class="CheckIn-card">
      <%= simple_form_for [@booking, @precheckin] do |f| %>
        <input type="hidden" name="authencity_token" id="<%= form_authenticity_token %>">
        <input type="hidden" name="submission[stripe_payment_id]" id="payment">

        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :email %>

        <div id='card'></div>

        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>



<script charset="utf-8">
  var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
  // load the fonts in
  var fonts = [{
    cssSrc: "https://fonts.googleapis.com/css?family=Karla",
  }];
  // styles for the stripe inputs
  var styles = {
    base: {
        color: "#32325D",
        fontWeight: 500,
        fontFamily: "Inter, Open Sans, Segoe UI, sans-serif",
        fontSize: "16px",
        fontSmoothing: "antialiased",

        "::placeholder": {
          color: "#CFD7DF"
        }
      },
      invalid: {
        color: "#E25950"
      },
  }

  var elements = stripe.elements();
  var cardElement = elements.create('card', {
    style: styles,
    hidePostalCode: true,
  });
  cardElement.mount('#card');

  const form = document.querySelector('#new_precheckin');
  form.addEventListener('submit', function(event) {
    event.preventDefault();
    // POST request
    fetch('/payment_intents', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        authenticity_token: '<%= form_authenticity_token %>',
      }),
    })
    .then((response) => response.json())
    .then((paymentIntent) => {
      stripe.confirmCardPayment(
        paymentIntent.client_secret, {
          payment_method: {
            card: cardElement
          }
        }
      ).then((response) => {
        if (response.error) {
          alert(response.error.message);
        } else {
          const paymentIdInput = document.querySelector('#payment');
          paymentIdInput.value = paymentIntent.id;
          form.submit();
        }
      })
    })
    .catch((error) => {
      console.error('Error:', error);
    });
  });
</script>

app/views/precheckins/show.html.erb
<h1>this is the show boyy</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>